// Generated by CoffeeScript 1.9.0
(function() {
  (function($) {
    var def_options, user_options;
    def_options = {
      speed: 500,
      auto: true,
      direction_for_auto: "next"
    };
    return user_options = $.fn.slider = function(params) {
      var btn_next, btn_prev, el_number, el_width, elems, init, inner, makeStepNext, makeStepPrev, options, outer, timer;
      options = $.extend({}, def_options, user_options);
      outer = "";
      btn_prev = "";
      btn_next = "";
      timer = "";
      inner = $(this);
      elems = inner.children();
      el_width = elems.eq(0).width();
      el_number = elems.length;
      init = function() {
        var bindEvents, makeNavigation, makeSliderWrap;
        bindEvents = function() {
          btn_prev.on("click", makeStepPrev);
          btn_next.on("click", makeStepNext);
          outer.hover(function() {
            btn_prev.stop(true).fadeIn();
            btn_next.stop(true).fadeIn();
            return console.log("btns fadeIn");
          }, function() {
            btn_prev.stop(true).fadeOut();
            btn_next.stop(true).fadeOut();
            return console.log("btns fadeOut");
          });
          return console.log("Bind events");
        };
        makeSliderWrap = function() {
          inner.wrap("<div class='slider__wrp'></div>");
          outer = inner.parent();
          return console.log("Make slider wrap");
        };
        makeNavigation = function() {
          outer.append("<div class='slider__btn_prev'></div><div class='slider__btn_next'></div>");
          btn_prev = $(".slider__btn_prev");
          btn_next = $(".slider__btn_next");
          return console.log("Make navigation");
        };
        makeSliderWrap();
        makeNavigation();
        bindEvents();
        if (options.auto === true) {
          return timer = setInterval(function() {
            if (options.direction_for_auto === "next") {
              btn_next.trigger("click", [true]);
            }
            if (options.direction_for_auto === "prev") {
              return btn_prev.trigger("click", [true]);
            }
          }, 3000);
        }
      };
      makeStepPrev = function(event, auto) {
        var last_el, makeFirst;
        if (auto !== true) {
          clearInterval(timer);
        }
        last_el = inner.children().last();
        makeFirst = function() {
          return inner.prepend(last_el.css({
            "marginLeft": -el_width
          }));
        };
        makeFirst();
        inner.children().eq(0).animate({
          "margin": 0
        }, options.speed);
        return console.log("make step prev");
      };
      makeStepNext = function(event, auto) {
        var first_el, makeLast;
        if (auto !== true) {
          clearInterval(timer);
        }
        first_el = inner.children().eq(0);
        makeLast = function() {
          return inner.append(first_el.css({
            "margin": 0
          }));
        };
        first_el.animate({
          "marginLeft": -el_width
        }, options.speed, makeLast);
        return console.log("make step next");
      };
      init();
      return this;
    };
  })(jQuery);

}).call(this);
